- hosts: monitoring.marekexample.com
  become: True
  roles:
    - role: cloudalchemy.prometheus
      vars:
         prometheus_targets:
            node:
            - targets:
              - monitoring.marekexample.com:9100
              - packstack.marekexample.com:9100
              - green.marekexample.com:9100
              - minikube.marekexample.com:9100
              - tower.marekexample.com:9100
              - cf.marekexample.com:9100
              - engine.marekexample.com:9100
              labels:
                env: marekexample
    - role: cloudalchemy.grafana
      vars:
         grafana_security:
            admin_user: admin
            admin_password: admin
         grafana_datasources:
          - name: prometheus
            type: prometheus
            access: proxy
            url: 'http://localhost:9090'
            basicAuth: false
         grafana_dashboards:
          - dashboard_id: 10645
            revision_id: 1
            datasource: prometheus
          - dashboard_id: 5984
            revision_id: 1
            datasource: prometheus
          - dashboard_id: 1860
            revision_id: 14
            datasource: prometheus
          - dashboard_id: 405
            revision_id: 8
            datasource: prometheus
          - dashboard_id: 10242
            revision_id: 1
            datasource: prometheus
          - dashboard_id: 10204
            revision_id: 2
            datasource: prometheus

- name: install node exporter on all
  hosts: all
  ignore_unreachable: True
  roles:
    - cloudalchemy.node-exporter
