- hosts: green.marekexample.com
  gather_facts: false
  roles:
    - role: ovirt_vm
    - role: ovirt_tag

- hosts: "{{ vm_name }}"
  gather_facts: False
  tasks:
    - name: cloud-init fix 1
      yum:
        name: cloud-init
        state: absent
  
    - name: cloud-init fix 2
      template:
        src: ovirt_vm/templates/nic.j2
        dest: /etc/sysconfig/network-scripts/ifcfg-eth0
        owner: root
        group: root
        mode: '0644'
  
- hosts: "{{ vm_name }}"
  gather_facts: False
  vars:
    ssh_keys_root:
      - "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
      - "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa_ubuntu.pub') }}"
  roles:
    - role: ovirt_ssh_keys
