# this playbok creates db_admin and app_admin account on 2 servers
# password for every user is different
# first user is created with variable that vault stores locally in /root dir
# second type user has password set by encrypting string
# vault files are created and will be provided to admins

- name: configure db1,app1 accounts using vaulted vars file
  hosts: all
  gather_facts: False
  tasks:

    - name: hash password 1
      debug:
        msg: "{{ vault_user1pass | password_hash('sha512') }}"
      register: hashed_password

    - name: show hashed pass
      debug:
        msg: "{{ hashed_password }}"

    - name: create account 1
      user:
        name: "{{ user1name }}"
        password: "{{ hashed_password.msg }}"


- name: set 2nd password
  hosts: learnansible1.marekexample.com
  vars:
    app2password:   !vault |
          $ANSIBLE_VAULT;1.2;AES256;app1
          36383932306234306230353832373064323062613561393438373130396233666434383833366230
          6330643362373437353165316431343530623938326365300a396637326362633364383564313836
          61346438303666353835373965393231343266633034373237353734646338323165336238626134
          6435333062623365350a303538663136626333636336313866646335386236623936613938306165
          6235
  gather_facts: False
  tasks:

    - name: debug 2nd pass
      debug:
        msg: "{{ app2password }}"
      register: output2


    - name: hash password 2
      debug:
        msg: "{{ output2.msg | password_hash('sha512') }}"
      register: hashed_password2


    - name: show hashed pass
      debug:
        msg: "{{ hashed_password2 }}"

    - name: create account 2
      user:
        name: app2
        password: "{{ hashed_password2.msg }}"
