---
# tasks file for nfs_server

- name: copy config
  copy:
    src: chrony.conf
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'

- name: Set timezone 
  timezone:
    name: Europe/Warsaw
