- hosts: green.marekexample.com
  become: true
  become_user: root
  gather_facts: false
  tasks:

    - import_role:
        name: ovirt_vm

- hosts: packstack.marekexample.com
  become: true
  become_user: root
  gather_facts: false
  tasks:

    - import_role:
        name: marekexample_packstack

    - import_role:
        name: packstack
