---

- name: set hostname
  hostname:
    name: packstack.marekexample.com

- name: Set authorized key taken from file
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

- name: set root password
  user:
    name: root
    password: "{{ rootpw | password_hash('sha512')  }}"


#- name: 1
#  import_tasks: install_package.yml 

#- name: 2
#  import_tasks: firewall_rules.yml

#- name: 3
#  import_tasks: configure_service.yml

#- name: 4
#  import_tasks: enable_service.yml
