---
# tasks file for nfs_server

- name: enable firewall
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: true
  with_items:
    - nfs
    - mountd
    - rpc-bind
