---
# tasks file for nfs_server

- name: enable systemd
  systemd:
    name: "{{ item }}" 
    state: started
    enabled: yes
  with_items:
    - nfs-server
    - nfs-lock
    - nfs-idmap
    - rpcbind
