---
# tasks file for nfs_server

- name: install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

#- name: Add repository
#  yum_repository:
#    name: docker-ce
#    description: docker CE
#    baseurl: https://download.docker.com/linux/centos/docker-ce.repo

- name: add repo
  shell: wget -P /etc/yum.repos.d  https://download.docker.com/linux/centos/docker-ce.repo 

- name: install packages 2
  yum:
    name: "{{ item }}"
    state: present
    disable_gpg_check: yes
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
