- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - import_role:
        name: ssh_keys

    - import_role:
        name: linux_standard

    - import_role:
        name: ntp_client
