# prerequis
# ## create /etc/openstack/clouds.yaml. define admin cloud and variables from /root/keystonerc_admin:
# project_name: OS_PROJECT_NAME=admin
# username: OS_USERNAME (admin
# password: OS_PASSWORD (aebf1e532bc147a2)
# region_name RegionOne (fixed)
# auth_url: OS_AUTH_URL but on url: http://192.168.122.10:35357/ and different port

### now copy template br-ex
#
- name: disable services
  systemd:
    name: "{{ item }}"
    state: stopped
    masked: yes
  with_items:
    - firewalld
    - NetworkManager
  ignore_errors: yes


- name: start services
  systemd:
    name: network
    state: started


- name: install openstacksdk
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - https://rdoproject.org/repos/rdo-release.rpm

- name: install openstacksdk
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - centos-release-openstack-stein

- name: update all packages
  yum:
    name: '*'
    state: latest


- name: install openstack-packstack
  yum:
    name: openstack-packstack
    state: present



- name: copy template
  template:
     src: packstack-latest.j2
     dest: /root/packstack-latest

- name: install packstack
  shell: packstack --answer-file=/root/packstack-latest

  #- name: deploy br-ex
  #  template:
  #  src: br-ex.j2
  #  dest: /etc/sysconfig/network-scripts/ifcfg-br-ex
  #  backup: yes

  #- name: deploy eth0
  #template:
  #  src: eth0.j2
  #  dest: /etc/sysconfig/network-scripts/ifcfg-eth0
  #  backup: yes

- name: reboot
  shell: systemctl reboot

  # doesn't continue on reboot
- name: install openstacksdk
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python2-shade
    - python2-openstacksdk
