- name: Reboot a host and wait for it to return
  shell: shutdown -r now

# This pause is mandatory, otherwise the existing control connection gets reused!
- name: wait 180s
  pause: seconds=180

    # Now we will run a local 'ansible -m ping' on this host until it returns.
    # This works with the existing ansible hosts inventory and so any custom ansible_ssh_hosts definitions are being used
- name: test ping 
  ping:
  register: result
  until: result.rc == 0
  retries: 30
  delay: 10

    # And finally, execute 'uptime' when the host is back.
- name: check if host back
  shell: uptime
