---
# tasks file for nfs_server

- name: install ovirt 42
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - https://resources.ovirt.org/pub/yum-repo/ovirt-release42.rpm
  tags:
    - packages
