---
# tasks file for nfs_server

- name: install nfs package
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - bind
    - bind-utils
    - NetworkManager-glib
  tags:
    - packages
