---
- hosts: "{{ download_host }}"
  gather_facts: True
  tasks:
    - import_role:
        name: download_file

- hosts: localhost
  connection: local
  gather_facts: True
  tasks:
    - import_role:
        name: openstack_image_upload
