- name: cloud-init fix 1
  yum:
    name: cloud-init
    state: absent

- name: cloud-init fix 2
  template:
    src: nic.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    owner: root
    group: root
    mode: '0644' 
