---
- name: include ovirt password
  no_log: true
  include_vars: ovirt_password.yml
- name: auth in engine
  block:

       - name: Obtain SSO token with using username/password credentials
         ovirt_auth:
           url: https://engine.marekexample.com/ovirt-engine/api
           username: admin@internal
           password: "{{ ovirt_password }}"

       - name: Run VM with cloud init, with multiple network interfaces
         ovirt_vm:
           auth: "{{ ovirt_auth }}"
           name: "{{ vm_name }}"
           template: "{{ template }}"
           clone: yes
           state: running
           cluster: Default
           memory: "{{ mem_standard }}GiB"
           memory_guaranteed: "{{ mem_standard }}GiB"
           cpu_cores: "{{ cpu_cores}}"
           high_availability: true
           cloud_init_persist: false
           cloud_init:
             nic_name: "{{ nic_name }}"
             nic_boot_protocol: static
             nic_ip_address: "{{ ip_addr }}"
             nic_netmask: 255.255.255.0
             nic_gateway: 192.168.0.1
             nic_on_boot: true
             dns_servers: 192.168.0.212 192.168.0.1
             dns_search: marekexample.com
             custom_script: |
               write_files:
                - content: |
                  Hello, world!
                  path: /etc/cloud/cloud-init.disabled
                  permissions: '0644'
                - content: |
                    network: {config: disabled} 
                  path: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg 
                  permissions: '0700'
             host_name: "{{ vm_name }}"
             authorized_ssh_keys: "{{ lookup('file', 'sshkeys') }}"
             user_name: root
             root_password:  redhat01
           graphical_console: 
             protocol:
               - spice
               - vnc
           type: server
           wait: true
           operating_system: other_linux
           serial_console: true
           cloud_init_nics:
           - nic_name: "{{ nic_name }}"

             #       - name: wait admin to manually start server (obirt bug)
             #pause:
             #seconds: 120 

  always:
      - name: Always revoke the SSO token
        ovirt_auth:
          state: absent
          ovirt_auth: "{{ ovirt_auth }}"

