- name: HEARTBEAT deploy config template
  ansible.builtin.template:
    src: heartbeat.j2
    dest: /etc/heartbeat/heartbeat.yml
    owner: root
    group: root
    mode: '0600'
    backup: yes
    validate: /usr/bin/heartbeat test config -c %s

- name: HEARTBEAT setup assets
  shell: /usr/bin/heartbeat setup
  ignore_errors: yes

- name:  HEARTBEAT restart service
  ansible.builtin.systemd:
    name: heartbeat-elastic
    state: restarted
    enabled: yes
  ignore_errors: yes
