---
# tasks file for beats

- name: install packages
  import_tasks: install_beats_packages.yml


- name: deploy filebeat configuration
  import_tasks: configure_filebeat.yml


- name: deploy metricbeat configuration
  import_tasks: configure_metricbeat.yml

- name: deploy heartbeat configuration
  import_tasks: configure_heartbeat.yml
