---
# tasks file for beats

- name: install packages
  import_tasks: packages.yml


- name: deploy filebeat configuration
  import_tasks: filebeat.yml

- name: deploy metricbeat configuration
  import_tasks: metricbeat.yml

- name: deploy heartbeat configuration
  import_tasks: heartbeat.yml

- name: deploy packetbeat configuration
  import_tasks: packetbeat.yml
