- name: install package
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - NetworkManager-glib
  tags:
    - packages

- name: adjust non-managed nic
  lineinfile:
    path: "/etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}"
    regexp: '^DNS[12]='
    state: absent

- name: adjust non-managed nic 2
  blockinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-ovirtmgmt
    block: |
      DNS2=192.168.0.212
      DNS2=192.168.0.1
    state: present 

- name: restart network
  systemd:
    name: network
    state: reloaded
