- hosts: packstack.marekexample.com
  gather_facts: false
  user: root
  become: yes
  become_method: sudo 
  tasks:
    - import_role:
        name: marekexample_packstack

    - import_role:
        name: cloudinit_disable

    - import_role:
        name: ntp_client

    - import_role:
        name: dns_client
