### ansible-playbook -i inventory/ovirt4.py simple_playbooks/conditionals_1.yml
- name: 1
  hosts: tag_ubuntu
  remote_user: ubuntu
  tasks:
     - name: check uptime using default cloud image user UBUNTU
       shell: uptime
     - name: display inv variable UBUNTU
       debug:
          msg: "{{ os_type }}"

- name: 2
  hosts: tag_redhat
  remote_user: centos
  tasks:
     - name: check uptime using default cloud image user REDHAT
       shell: uptime
     - name: display inv variable REDHAT
       debug:
          msg: "{{ os_type }}"



- name: 3
  hosts: all
  tasks:           
  - name: show free mb
    debug:
      var: "{{ ansible_facts['memfree_mb'] }}"
  
  - name: inform that host is capable when free mem is > than 100MB
    debug:
       msg: "host is capable to run webserver"
    when: ansible_memfree_mb > 900

  - name: inform that host is NOT capable when free mem is > than 100MB
    debug:
       msg: "host is NOT capable to run webserver"
    when: ansible_memfree_mb < 900
