- name: deploy custom facts on learnansible1
  hosts: all
  tasks:

      - name: create dir
        file:
          state: directory
          recurse: yes
          path: /etc/ansible/facts.d/

      - name: deploy facts
        copy:
          src: learnansible1.fact
          dest: /etc/ansible/facts.d/
        
      - name: debug
        debug:
          var: "ansible_facts.ansible_local.learnansible1.serverroles.role1"


      - name: install packages from facts
        package:
          name: apache2
          state: "{{ ansible_facts.ansible_local.learnansible1.packages.state }}"
        when:  ' ansible_facts.ansible_local.learnansible1.serverroles.role1 == "app1" and ansible_distribution ==  "Ubuntu" '

      - name: debug localhost values
        debug:
          msg: "facts from localhost are {{ hostvars['localhost'] }}"

      - name: custom index.html
        copy:
          content: "Allowed access from {{ hostvars[localhost]['ansible_facts']['ansible_all_ipv4_addresses'] }} "
          dest: '/var/www/html/index.html'
