- name: show few os facts
  gather_facts: true
  hosts: learnansible
  become: true
  become_user: root
  tasks:
    - name: show ip
      debug:
              #        msg: "{{ ansible_facts.cmdline['BOOT_IMAGE'] }}"
         msg: "{{ ansible_default_ipv4.address }}"


    - name: hostvars
      debug:
         msg: "{{ hostvars }}"

