- hosts: all
  tasks:
     - name: create new file
       user:
          name: tester
       notify: 
         - inform new user


  handlers:
   - name: inform new user
     debug:
       msg: "hurra!" 
